linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable:
    - lll
    - gofmt
    - gosec
    - govet
    - golint
    - gocyclo
    - goconst
    - misspell
    - maligned
    - errcheck
    - deadcode
    - unconvert
    - megacheck
    - staticcheck
    - gochecknoinits

run:
  skip-dirs:
    - vendor 

issues:
  exclude:
    - 'shadow: declaration of "(err|ctx)" shadows declaration at'
